name: Push Metrics to Grafana Cloud

on:
  push:
    branches:
      - main
    paths:
      - 'github_flakiness_*.json'
      - 'gitlab_flakiness_*.json'

  # Allow manual trigger
  workflow_dispatch:

permissions:
  contents: read

jobs:
  push-to-grafana:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install prometheus-client requests

      - name: Start Pushgateway
        run: |
          echo "🚀 Starting Pushgateway..."
          docker run -d --name pushgateway -p 9091:9091 prom/pushgateway
          sleep 5

      - name: Push metrics to Pushgateway
        run: |
          echo "📊 Processing metrics from JSON files..."
          python3 push_json_to_prometheus.py

      - name: Push to Grafana Cloud
        env:
          GRAFANA_CLOUD_URL: ${{ secrets.GRAFANA_CLOUD_URL }}
          GRAFANA_CLOUD_USER: ${{ secrets.GRAFANA_CLOUD_USER }}
          GRAFANA_CLOUD_TOKEN: ${{ secrets.GRAFANA_CLOUD_TOKEN }}
        run: |
          echo "📡 Pushing metrics from Pushgateway to Grafana Cloud..."
          python3 push_to_grafana_cloud.py
